module.exports = [
  {
    authorized: true,
    title: 'hzero.common.title.themeConfig',
    path: '/theme-config',
    key: '/theme-config',
    component: () => import('../routes/ThemeConfigCenter'),
    models: [],
  },
  {
    path: '/exception/403',
    component: () => import('../routes/Exception/403'),
    models: [() => import('../models/error')],
  },
  {
    path: '/exception/404',
    component: () => import('../routes/Exception/404'),
    models: [() => import('../models/error')],
  },
  {
    path: '/exception/500',
    component: () => import('../routes/Exception/500'),
    models: [() => import('../models/error')],
  },
  {
    path: '/exception/501',
    component: () => import('../routes/Exception/501'),
    models: [() => import('../models/error')],
    key: '/exception/501',
    title: 'hzero.common.title.exception501',
    authorized: true,
  },
  {
    path: '/exception/trigger',
    component: () => import('../routes/Exception/triggerException'),
    models: [() => import('../models/error')],
  },
  {
    path: '/link/:link',
    component: () => import('../routes/Link'),
  },
  {
    path: '/workplace',
    component: () => import('../routes/Dashboard/Workplace'),
    models: [() => import('../models/workplace')],
  },
  {
    authorized: true,
    path: '/public/unauthorized',
    component: () => import('../routes/TokenExpired'),
    key: '/public/unauthorized',
    models: [],
  },
  {
    authorized: true,
    path: '/public/kickoff',
    component: () => import('../routes/Kickoff'),
    key: '/public/kickoff',
    models: [],
  },
  {
    authorized: true,
    path: '/public/self-error',
    component: () => import('../routes/SelfError'),
    key: '/public/self-error',
  },
  {
    authorized: true,
    title: 'hadm.marketclient.view.market.client',
    path: '/market-client',
    key: '/market-client',
    models: [],
    components: [
      {
        title: 'hadm.marketclient.view.market.client',
        path: '/market-client/home',
        key: '/market-client/home',
        component: () => import('../routes/MarketClient/Home'),
        models: [() => import('../models/market')],
      },
      {
        title: 'hadm.marketclient.view.home.productList',
        path: '/market-client/product-list',
        key: '/market-client/product-list',
        component: () => import('../routes/MarketClient/ProductList'),
        models: [],
      },
      {
        title: 'hadm.marketclient.view.service.list',
        path: '/market-client/services-list',
        key: '/market-client/services-list',
        component: () => import('../routes/MarketClient/ServiceList'),
        models: [],
      },
      {
        title: '服务详情',
        path: '/market-client/services-detail/:serviceId',
        key: '/market-client/services-detail/:serviceId',
        component: () => import('../routes/MarketClient/ServiceList/Detail'),
        models: [],
      },
      {
        title: '组件/接口/配置对比',
        path: '/market-client/compare/:serviceId/:version',
        key: '/market-client/compare/:serviceId/:version',
        component: () => import('../routes/MarketClient/ServiceList/Compare'),
        models: [],
      },
      {
        title: '无网络',
        path: '/market-client/offline',
        key: '/market-client/offline',
        component: () => import('../routes/MarketClient/OfflinePage'),
        models: [],
      },
      {
        title: 'hadm.marketclient.view.feedback.title',
        path: '/market-client/feedback',
        key: '/market-client/feedback',
        component: () => import('../routes/MarketClient/Feedback'),
        models: [],
      },
    ],
  },
];
