/**
 * 集值
 */
export default {
  // 账单状态
  BillStatus: 'HCHG.BILL.STATUS',
  // 支付状态
  BillPaymentStatus: 'HCHG.BILL.PAYMENT_STATUS',
  // 账单发生实体
  BillEntityType: 'HCHG.BILL.ENTITY_TYPE',
  // 账单计量单位
  BillIssueUom: 'HCHG.BILL.ISSUE_UOM',
  // 账单优惠类型
  BillDiscountType: 'HCHG.BILL.DISCOUNT_TYPE',
  // 币种
  Currency: 'HPFM.CURRENCY',
  // 账户类型
  AccountType: 'HCHG.ACCOUNT.ACCOUNT_TYPE',
  // 启用/禁用
  EnabledFlag: 'HPFM.ENABLED_FLAG',
  // 计费规则状态
  RuleStatus: 'HCHG.RULE.STATUS',
  // 折扣类型
  DiscountType: 'HCHG.DISCOUNT.TYPE',
  // 付费模式
  RulePaymentModel: 'HCHG.RULE.PAYMENT_MODEL',
  // 计费方式
  RuleChargeMethod: 'HCHG.RULE.CHARGE_METHOD',
  // 计费类型
  RuleChargeType: 'HCHG.RULE.CHARGE_TYPE',
  // 计费单位
  RuleChargeUnit: 'HCHG.RULE.CHARGE_UNIT',
  // 生效范围
  DiscountEffectiveRange: 'HCHG.DISCOUNT.EFFECTIVE_RANGE',
  // 账号
  AccountBalance: 'HCHG.ACCOUNT_BALANCE',
  // 账号租户级
  AccountBalanceOrg: 'HCHG.ACCOUNT_BALANCE.ORG',
  // 生效的账号(平台级)
  EffectiveAccount: 'HCHG.ACCOUNT.EFFECTIVE',
  // 生效的账号(租户级)
  EffectiveAccountOrg: 'HCHG.ACCOUNT.EFFECTIVE.ORG',
  // 账号平台级
  Account: 'HCHG.ACCOUNTS',
  // 账号租户级
  AccountOrg: 'HCHG.ACCOUNTS.ORG',
  // 支付渠道
  PaymentChannel: 'HPAY.PAYMENT_CHANNEL',
  // 充值状态
  AccountRechargeStatus: 'HCHG.ACCOUNT.RECHARGE.STATUS',
  // 扣款状态
  AccountDebitStatus: 'HCHG.ACCOUNT.DEBIT_STATUS',
  // 用户
  User: 'HIAM.SITE.USER',
  // 租户
  Tenant: 'HPFM.TENANT_ENCRYPT',
  // 租户
  TenantEncrypt: 'HPFM.TENANT_ENCRYPT',
  // 来源系统
  SourceSystem: 'HCHG.SOURCE_SYSTEM',
  // 账单
  BillHeader: 'HCHG.BILL_HEADER',
  // 回调状态
  BillCallbackStatus: 'HCHG.BILL.CALLBACK_STATUS',
  // 规则头平台级
  ruleHeader: 'HCHG.RULE_HEADER',
  // 规则头租户级
  ruleHeaderOrg: 'HCHG.RULE_HEADER.ORG',
};
