module.exports = [
  {
    path: '/hiam/client',
    component: () => import('../routes/Client'),
    models: [() => import('../models/client')],
  },
  {
    path: '/private/hiam/client',
    authorized: true,
    component: () => import('../routes/Client'),
    models: [() => import('../models/client')],
  },
  {
    path: '/hiam/tenant/redirect',
    component: () => import('../routes/TenantRedirect'),
    authorized: true,
    title: 'redirect',
    models: [() => import('../models/tenantRedirect')],
  },
  {
    path: '/hiam/doc-type',
    component: () => import('../routes/DocType'),
    models: [() => import('../models/docType')],
  },
  {
    path: '/private/hiam/doc-type',
    authorized: true,
    component: () => import('../routes/DocType'),
    models: [() => import('../models/docType')],
  },
  {
    path: '/hiam/doc-dimension',
    component: () => import('../routes/DocDimension'),
    models: [() => import('../models/docDimension')],
  },
  {
    path: '/private/hiam/doc-dimension',
    authorized: true,
    component: () => import('../routes/DocDimension'),
    models: [() => import('../models/docDimension')],
  },
  {
    path: '/hiam/label-management',
    component: () => import('../routes/LabelManagement'),
  },
  {
    path: '/hiam/ldap',
    component: () => import('../routes/LDAP'),
    models: [() => import('../models/ldap')],
  },
  {
    path: '/private/hiam/ldap',
    authorized: true,
    component: () => import('../routes/LDAP'),
    models: [() => import('../models/ldap')],
  },
  {
    path: '/hiam/menu',
    component: () => import('../routes/MenuConfig'),
    models: [() => import('../models/menuConfig')],
  },
  {
    path: '/private/hiam/menu',
    authorized: true,
    component: () => import('../routes/MenuConfig'),
    models: [() => import('../models/menuConfig')],
  },
  {
    path: '/hiam/api-management',
    component: () => import('../routes/ApiManagement'),
    models: [],
  },
  {
    path: '/private/hiam/api-management',
    authorized: true,
    component: () => import('../routes/ApiManagement'),
    models: [],
  },
  {
    path: '/private/hiam/miss-permission-record',
    authorized: true,
    models: [],
    components: [
      {
        path: '/private/hiam/miss-permission-record/list',
        authorized: true,
        component: () => import('../routes/MissPermissionRecord'),
        models: [],
      },
      {
        path: '/private/hiam/miss-permission-record/detail/:permissionCheckId',
        authorized: true,
        component: () => import('../routes/MissPermissionRecord/Detail'),
        models: [],
      },
    ],
  },
  {
    path: '/hiam/miss-permission-record',
    models: [],
    components: [
      {
        path: '/hiam/miss-permission-record/list',
        component: () => import('../routes/MissPermissionRecord'),
        models: [],
      },
      {
        path: '/hiam/miss-permission-record/detail/:permissionCheckId',
        component: () => import('../routes/MissPermissionRecord/Detail'),
        models: [],
      },
    ],
  },
  {
    path: '/hiam/open-app',
    component: () => import('../routes/OpenApp'),
    models: [() => import('../models/openApp')],
  },
  {
    path: '/private/hiam/open-app',
    authorized: true,
    component: () => import('../routes/OpenApp'),
    models: [() => import('../models/openApp')],
  },
  {
    path: '/hiam/password-policy',
    component: () => import('../routes/PasswordPolicy'),
    models: [() => import('../models/passwordPolicy')],
  },
  {
    path: '/private/hiam/password-policy',
    authorized: true,
    component: () => import('../routes/PasswordPolicy'),
    models: [() => import('../models/passwordPolicy')],
  },
  {
    path: '/hiam/role',
    components: [
      {
        path: '/hiam/role/list',
        component: () => import('../routes/RoleManagement'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/roleManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityCompany'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPurorg'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPuragent'),
          () => import('../models/roleDataAuthority/roleDataAuthorityValueList'),
          () => import('../models/roleDataAuthority/roleDataAuthorityLovView'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataSource'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityCompany'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataSource'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityLovView'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPuragent'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPurorg'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityValueList'),
        ],
      },
      {
        path: '/hiam/role/api/:roleId',
        component: () => import('../routes/RoleManagement/ApiField'),
        models: [() => import('../models/roleManagement')],
      },
      {
        path: '/hiam/role/field/:roleId/:permissionId',
        component: () => import('../routes/RoleManagement/ApiField/FieldPermission'),
        models: [() => import('../models/roleManagement')],
      },
    ],
  },
  {
    path: '/private/hiam/role',
    authorized: true,
    components: [
      {
        path: '/private/hiam/role/list',
        authorized: true,
        component: () => import('../routes/RoleManagement'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/roleManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityCompany'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPurorg'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPuragent'),
          () => import('../models/roleDataAuthority/roleDataAuthorityValueList'),
          () => import('../models/roleDataAuthority/roleDataAuthorityLovView'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataSource'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityCompany'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataSource'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityLovView'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPuragent'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPurorg'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityValueList'),
        ],
      },
      {
        path: '/private/hiam/role/api/:roleId',
        authorized: true,
        component: () => import('../routes/RoleManagement/ApiField'),
        models: [() => import('../models/roleManagement')],
      },
      {
        path: '/private/hiam/role/field/:roleId/:permissionId',
        authorized: true,
        component: () => import('../routes/RoleManagement/ApiField/FieldPermission'),
        models: [() => import('../models/roleManagement')],
      },
    ],
  },
  {
    path: '/hiam/role-tree',
    components: [
      {
        path: '/hiam/role-tree/list',
        component: () => import('../routes/RoleManagement/TreeList'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/roleManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityCompany'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPurorg'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPuragent'),
          () => import('../models/roleDataAuthority/roleDataAuthorityValueList'),
          () => import('../models/roleDataAuthority/roleDataAuthorityLovView'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataSource'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityCompany'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataSource'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityLovView'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPuragent'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPurorg'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityValueList'),
        ],
      },
      {
        path: '/hiam/role-tree/api/:roleId',
        component: () => import('../routes/RoleManagement/ApiField'),
        models: [() => import('../models/roleManagement')],
      },
      {
        path: '/hiam/role-tree/field/:roleId/:permissionId',
        component: () => import('../routes/RoleManagement/ApiField/FieldPermission'),
        models: [() => import('../models/roleManagement')],
      },
    ],
  },
  {
    path: '/private/hiam/role-tree',
    authorized: true,
    components: [
      {
        path: '/private/hiam/role-tree/list',
        authorized: true,
        component: () => import('../routes/RoleManagement/TreeList'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/roleManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityManagement'),
          () => import('../models/roleDataAuthority/roleDataAuthorityCompany'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPurorg'),
          () => import('../models/roleDataAuthority/roleDataAuthorityPuragent'),
          () => import('../models/roleDataAuthority/roleDataAuthorityValueList'),
          () => import('../models/roleDataAuthority/roleDataAuthorityLovView'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataSource'),
          () => import('../models/roleDataAuthority/roleDataAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityCompany'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataGroup'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityDataSource'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityLovView'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPuragent'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityPurorg'),
          () => import('../models/securityGroupAuthority/secGrpAuthorityValueList'),
        ],
      },
      {
        path: '/private/hiam/role-tree/api/:roleId',
        authorized: true,
        component: () => import('../routes/RoleManagement/ApiField'),
        models: [() => import('../models/roleManagement')],
      },
      {
        path: '/private/hiam/role-tree/field/:roleId/:permissionId',
        authorized: true,
        component: () => import('../routes/RoleManagement/ApiField/FieldPermission'),
        models: [() => import('../models/roleManagement')],
      },
    ],
  },

  {
    path: '/hiam/domain-config',
    models: [],
    components: [
      {
        path: '/hiam/domain-config/list',
        component: () => import('../routes/SSOConfig'),
        models: [() => import('../models/ssoConfig')],
      },
      {
        path: '/hiam/domain-config/template/:domainId/:tenantId',
        component: () => import('../routes/SSOConfig/Template'),
        models: [() => import('../models/ssoConfig')],
        exact: true,
      },
      {
        path:
          '/hiam/domain-config/template/edit/:domainId/:tenantId/:templateAssignId/:templateName/:templatePath',
        component: () => import('../routes/SSOConfig/TemplateConfig'),
        models: [() => import('../models/ssoConfig')],
      },
    ],
  },
  {
    path: '/private/hiam/domain-config',
    authorized: true,
    models: [],
    components: [
      {
        path: '/private/hiam/domain-config/list',
        authorized: true,
        component: () => import('../routes/SSOConfig'),
        models: [() => import('../models/ssoConfig')],
      },
      {
        path: '/private/hiam/domain-config/template/:domainId/:tenantId',
        authorized: true,
        component: () => import('../routes/SSOConfig/Template'),
        models: [() => import('../models/ssoConfig')],
      },
      {
        path:
          '/private/hiam/domain-config/template/edit/:domainId/:tenantId/:templateAssignId/:templateName/:templatePath',
        authorized: true,
        component: () => import('../routes/SSOConfig/TemplateConfig'),
        models: [() => import('../models/ssoConfig')],
      },
    ],
  },
  {
    path: '/hiam/sub-account-org',
    models: [],
    components: [
      {
        path: '/hiam/sub-account-org/users',
        component: () => import('../routes/SubAccount/Org'),
        models: [
          () => import('../models/subAccountOrg'),
          () => import('../models/userInfo'),
          () => import('../models/authorityDimension'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityCompany'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityDataGroup'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityDataSource'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityLovView'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityPuragent'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityPurorg'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityValueList'),
        ],
      },
      {
        path: '/hiam/sub-account-org/authority-management',
        component: () => import('../routes/SubAccount/Org/AuthorityManagement'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/authorityManagement/authorityManagement'),
          () => import('../models/authorityManagement/authorityCompany'),
          () => import('../models/authorityManagement/authorityCustomer'),
          () => import('../models/authorityManagement/authoritySupplier'),
          () => import('../models/authorityManagement/authorityPurorg'),
          () => import('../models/authorityManagement/authorityPuragent'),
          () => import('../models/authorityManagement/authorityPurcat'),
          () => import('../models/authorityManagement/authorityLovView'),
          () => import('../models/authorityManagement/authorityValueList'),
          () => import('../models/authorityManagement/authorityDataSource'),
          () => import('../models/authorityManagement/authorityDataGroup'),
        ],
      },
      {
        path: '/hiam/sub-account-org/api-field',
        components: [
          {
            path: '/hiam/sub-account-org/api/:userId',
            component: () => import('../routes/SubAccount/Org/ApiField'),
            models: [() => import('../models/subAccountOrg')],
          },
          {
            path: '/hiam/sub-account-org/field/:userId/:permissionId',
            component: () => import('../routes/SubAccount/Org/ApiField/FieldPermission'),
            models: [() => import('../models/subAccountOrg')],
          },
        ],
      },
      {
        authorized: true,
        path: '/hiam/sub-account-org/data-import/:code',
        component: () => import('../routes/himp/CommentImport'),
        models: [],
      },
    ],
  },
  {
    path: '/private/hiam/sub-account-org',
    authorized: true,
    models: [],
    components: [
      {
        path: '/private/hiam/sub-account-org/users',
        authorized: true,
        component: () => import('../routes/SubAccount/Org'),
        models: [
          () => import('../models/subAccountOrg'),
          () => import('../models/userInfo'),
          () => import('../models/authorityDimension'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityCompany'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityDataGroup'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityDataSource'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityLovView'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityPuragent'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityPurorg'),
          () => import('../models/accountSecurityGroupAuthority/accSecGrpAuthorityValueList'),
        ],
      },
      {
        path: '/private/hiam/sub-account-org/authority-management',
        authorized: true,
        component: () => import('../routes/SubAccount/Org/AuthorityManagement'),
        models: [
          () => import('../models/authorityDimension'),
          () => import('../models/authorityManagement/authorityManagement'),
          () => import('../models/authorityManagement/authorityCompany'),
          () => import('../models/authorityManagement/authorityCustomer'),
          () => import('../models/authorityManagement/authoritySupplier'),
          () => import('../models/authorityManagement/authorityPurorg'),
          () => import('../models/authorityManagement/authorityPuragent'),
          () => import('../models/authorityManagement/authorityPurcat'),
          () => import('../models/authorityManagement/authorityLovView'),
          () => import('../models/authorityManagement/authorityValueList'),
          () => import('../models/authorityManagement/authorityDataSource'),
          () => import('../models/authorityManagement/authorityDataGroup'),
        ],
      },
      {
        path: '/private/hiam/sub-account-org/api-field',
        authorized: true,
        components: [
          {
            path: '/private/hiam/sub-account-org/api/:userId',
            authorized: true,
            component: () => import('../routes/SubAccount/Org/ApiField'),
            models: [() => import('../models/subAccountOrg')],
          },
          {
            path: '/private/hiam/sub-account-org/field/:userId/:permissionId',
            authorized: true,
            component: () => import('../routes/SubAccount/Org/ApiField/FieldPermission'),
            models: [() => import('../models/subAccountOrg')],
          },
        ],
      },
      {
        authorized: true,
        path: '/private/hiam/sub-account-org/data-import/:code',
        component: () => import('../routes/himp/CommentImport'),
        models: [],
      },
    ],
  },
  {
    path: '/hiam/sub-account-site',
    component: () => import('../routes/SubAccount/Site'),
    models: [() => import('../models/subAccount')],
  },
  {
    path: '/private/hiam/sub-account-site',
    authorized: true,
    component: () => import('../routes/SubAccount/Site'),
    models: [() => import('../models/subAccount')],
  },
  {
    path: '/hiam/user',
    models: [],
    components: [
      {
        authorized: true,
        title: 'hzero.common.title.userInfo',
        icon: 'user',
        key: '/hiam/user',
        path: '/hiam/user/info',
        component: () => import('../routes/UserInfo'),
        models: [() => import('../models/userInfo')],
      },
      {
        authorized: true,
        title: 'hzero.common.title.userInfo',
        icon: 'user',
        key: '/hiam/user',
        path: '/hiam/user/login-log',
        component: () => import('../routes/hpfm/PersonalLoginRecord'),
      },
    ],
  },
  {
    path: '/hiam/user-group-management',
    component: () => import('../routes/UserGroupManagement'),
    models: [() => import('../models/userGroupManagement')],
  },
  {
    path: '/private/hiam/user-group-management',
    authorized: true,
    component: () => import('../routes/UserGroupManagement'),
    models: [() => import('../models/userGroupManagement')],
  },
  // 租户维护 只有平台级
  {
    path: '/hiam/tenants',
    component: () => import('../routes/Tenants'),
    models: [() => import('../models/tenants')],
  },
  {
    path: '/hiam/tenant-init-config',
    component: () => import('../routes/TenantInitConfig'),
    models: [() => import('../models/tenantInitConfig')],
  },
  {
    path: '/hiam/tenant-init-log',
    component: () => import('../routes/TenantInitLog'),
    models: [() => import('../models/tenantInitLog')],
  },
  // 接口字段维护
  {
    path: '/hiam/api-field',
    models: [() => import('../models/hiamApiField')],
    components: [
      {
        path: '/hiam/api-field/list',
        models: [() => import('../models/hiamApiField')],
        component: () => import('../routes/ApiField'),
      },
      {
        path: '/hiam/api-field/:permissionId',
        models: [() => import('../models/hiamApiField')],
        component: () => import('../routes/ApiField/Field'),
      },
    ],
  },
  // 安全组维护
  {
    path: '/hiam/security-group',
    components: [
      {
        path: '/hiam/security-group/list',
        component: () => import('../routes/SecurityGroup/List/ListPage'),
      },
      {
        path: '/hiam/security-group/detail/:id/:roleId',
        component: () => import('../routes/SecurityGroup/Detail/DetailPage'),
      },
    ],
  },
  {
    path: '/hiam/tenant-menu-manage',
    models: [() => import('../models/tenantMenuManage'), () => import('../models/menuConfig')],
    components: [
      {
        component: () => import('../routes/TenantMenuManage'),
        path: '/hiam/tenant-menu-manage/list',
        models: [() => import('../models/tenantMenuManage'), () => import('../models/menuConfig')],
      },
      {
        component: () => import('../routes/TenantMenuManage/Detail'),
        path: '/hiam/tenant-menu-manage/detail/:id',
        models: [() => import('../models/tenantMenuManage'), () => import('../models/menuConfig')],
      },
    ],
  },
  {
    path: '/hiam/customer-management',
    component: () => import('../routes/CustomerManagement'),
    models: [],
  },
];
